# Generated by Django 3.2.3 on 2021-05-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.CharField(default=100, max_length=200),
        ),
    ]
